#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@myproject.com', 'Abcd@1234')" | python manage.py shell || true

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
